config/routes.rb
Rails.application.routes.draw do
  root 'users2#index'
  
  get 'users/main'
  get 'users/login'
  post 'users/login'
  root 'users#main'
  get 'users/logout'
  
  resources :users2, only: [:index, :new, :create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users2_controller.rb
class Users2Controller < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end
  
  def create
    
    user = User.create(uid: params[:user][:uid], pass: BCrypt::Password.create(params[:user][:pass]))
    redirect_to '/'
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def main
    if session[:login_uid]
      render :main
    else
      render :login
    end 
  end

  def login
    if User.find_by(uid: params[:uid])
      if BCrypt::Password.new(params[:user][:pass]) 
        session[:login_uid] = params[:uid]
        redirect_to root_path
      end 
    end 
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users2_helper.rb
module Users2Helper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/error.html.erb
ログイン失敗です!
<p>
    <%= link_to '戻る', :back %>
</p>

app/views/users/login.html.erb
<%= form_tag '/users/login', method: :post do %>
<%= label_tag :uid, 'ユーザーID' %>
<%= text_field_tag :uid %>
<p>
<%= label_tag :pass, 'パスワード' %>
<%= password_field_tag :pass %>
</p>

<%= submit_tag 'ログイン' %>
<% end %>

app/views/users/main.html.erb
ログイン成功です
<p>
    <%= link_to 'ログアウト', users_logout_path %>
</p>

app/views/users2/index.html.erb
<p><%= link_to 'ユーザー登録', new_users2_path %></p>
<p><%= link_to 'ログイン', users_login_path %></p>

app/views/users2/new.html.erb
<%= form_for @user , url: {action: :create} do |u| %>
    <%= u.label :uid, 'ユーザーID' %>
    <%= u.text_field :uid %>
    <%= u.label :pass, 'パスワード' %>
    <%= u.password_field :pass %>
    <%= u.submit '登録' %>
<% end %>